### ISSUE TITLE
Region not provided

### ISSUE THREAD

**Issue by chrisgeek** [awslabs/aws-rails-provisioner#19]
When trying to build, I get this error ```No region was provided. Configure the `:region` option or export the region name to ENV['AWS_REGION'] (Aws::Errors::MissingRegionError)``` I couldn't find it on the doc or anywhere online.

aws-rails-provisioner.yml
```
version: '0'

vpc:
  max_az: 2
  enable_dns: true
services:
  hospital-sys:
    source_path: ./hospital-sys
    fargate:
      desired_count: 3
      memory: 512
      cpu: 256
      envs:
        PORT: 80
        RAILS_LOG_TO_STDOUT: true
      public: true
    db_cluster:
      engine: aurora-postgresql
      db_name: app_development
    scaling:
      max_capacity: 5
      on_cpu:
        target_util_percent: 80
        scale_in_cool_down: 300
      on_requests:
        requests_per_target: 1000
```
