### ISSUE TITLE
CdkSampleInitStack was rollbacked.

### ISSUE THREAD

**Issue by yuuu** [awslabs/aws-rails-provisioner#7]
I created aws-rails-provisioner.yml like below and ran aws-rails-provisioner deploy.

```yml
version: '0'

vpc:
  max_az: 2
  enable_dns: true
services:
  provisioner_sample:
    source_path: ./app # relative path from `aws-rails-provisioner.yml`
    fargate:
      desired_count: 2
      memory: 512
      cpu: 256
      envs:
        PORT: 80
        RAILS_LOG_TO_STDOUT: true
      public: true
    scaling:
      max_capacity: 5
      on_cpu:
        target_util_percent: 80
        scale_in_cool_down: 300
      on_requests:
        requests_per_target: 1000
```

ROLLBACK has occurred in CdkSampleInitStack of CloudFormation. The details of the error are as follows.

```
ID: VpcapplicationSubnet2Subnet29670962

Value (ap-northeast-1b) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: ap-northeast-1c, ap-northeast-1d, ap-northeast-1a. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue; Request ID: ec4fb9e1-b9a6-4cd2-9393-b2348ac93068)
```

Probably, it is caused by the fact that ap-northeast-1b is not selectable among AZ of ap-northeast-1. Is there any workaround?
